name: Docker Image CI for main branch

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag agniveshadhikari/slinky:main-latest --tag agniveshadhikari/slinky:sha-$(git rev-parse --short HEAD)
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: agniveshadhikari
        password: ${{ secrets.DOCKERHUB_PAT }}
    
    - name: Push images to Docker Hub
      run: docker push -q agniveshadhikari/slinky --all-tags
