name: Docker Image CI for main branch

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Git: Checkout"
      uses: actions/checkout@v3

    - name: "Docker: Login to Docker Hub"
      uses: docker/login-action@v2
      with:
        username: agniveshadhikari
        password: ${{ secrets.DOCKERHUB_PAT }}
    
    - name: "Docker: Build and Push"
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          agniveshadhikari/slinky:sha-$(git rev-parse --short HEAD)
          agniveshadhikari/slinky:main-latest
      
